name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r backend/requirements.txt
          pytest backend -k "" || true

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Mobile
        working-directory: mobile
        run: flutter pub get

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Admin
        if: ${{ hashFiles('admin/package.json') != '' }}
        working-directory: admin
        run: |
          npm install
          npm run build
